### ISSUE TITLE
TypeScript #-imports supports

### ISSUE THREAD

**Issue by abdonrd** [samthor/but-unzip#1]
I see this comment regarding TypeScript doesn't support #-imports:

https://github.com/samthor/but-unzip/blob/dae8ae7aa8b6dbc4cfa55a6369c2ec4131afbee0/src/index.js#L2-L3

Could you share the issue link for TypeScript?
Thanks in advance!

**Comment by abdonrd** [comment]
Friendly ping to @samthor.

**Comment by samthor** [comment]
This is fixed: looks like package imports now works fine, as long as I set `moduleResolution` to "nodenext".

https://github.com/microsoft/TypeScript/issues/44848#issuecomment-1212826554

**Comment by abdonrd** [comment]
Oh, thats nice! Will you make a new release soon? Thanks!

**Comment by samthor** [comment]
The code won't change, actually - it was just a hint to TS.

The benefit of the package imports is that I already build twice:
- a version for the browser (that uses the built-in support in Chrome, and you need to provide `pako` otherwise)
- a version for Node (which Just Works™).

Check out "package.json" for the different imports. Most modern bundlers respect the browser/node distinction.
